### ISSUE TITLE
Custom Format with name CRiT skipped because another CF already exists with that name

### ISSUE THREAD

**Issue by jpdsc** [recyclarr/recyclarr#191] opened 2023-06-30 16:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `recyclarr sync` below warning is displayed on console:
`[WRN] Custom Format with name CRiT (Trash ID: 16622a6911d1ab5d5b8b713d5b0036d4) will be skipped because another CF already exists with that name (ID: 246). To fix the conflict, delete or rename the CF with the mentioned name`

I checked all the configs being used and nowhere else CRiT is being used with a different Trash ID.

### Expected Behavior

It should not give this warning because CRiT isn't being used as duplicate name with a different ID.

### Steps To Reproduce

1. Use the pre-made yml from: https://github.com/recyclarr/config-templates/blob/master/radarr/uhd-bluray-web.yml & https://github.com/recyclarr/config-templates/blob/master/radarr/hd-bluray-web.yml
2. Run `recyclarr sync`

### Environment & Versions

```bash
- Operating System: Debian + Official docker container 
- Architecture: x64
- Recyclarr Version: 5.1.1+Branch.tags-v5.1.1.Sha.4d0ce0d09f367ce2520eca53c4043568efa328fd
- Recyclarr Build: 5.1.1+Branch.tags-v5.1.1.Sha.4d0ce0d09f367ce2520eca53c4043568efa328fd
- Sonarr Version: 4.0.0.548
- Radarr Version: 4.6.3.7516
```

### Recyclarr Log File(s)

[recyclarr_2023-06-30_13-16-33.debug.log](https://github.com/recyclarr/recyclarr/files/11918359/recyclarr_2023-06-30_13-16-33.debug.log)
[cache.zip](https://github.com/recyclarr/recyclarr/files/11918369/cache.zip)
[configs.zip](https://github.com/recyclarr/recyclarr/files/11918415/configs.zip)
[recyclarr_2023-06-30_13-16-33.verbose.log](https://github.com/recyclarr/recyclarr/files/11918945/recyclarr_2023-06-30_13-16-33.verbose.log)

### Configuration YAML

```YAML
Added in the Log Files as configs.zip
```

**Comment by rcdailey** [comment] 2023-06-30 17:05
Could you attach the verbose log file too? Thank you!

**Comment by jpdsc** [comment] 2023-06-30 17:07
> Could you attach the verbose log file too? Thank you!

Done

**Comment by rcdailey** [comment] 2023-06-30 20:15
Thanks for those extra logs. After investigating, looks like the problem is the way you've set up the instances. You should not point 2 or more config instances at the same *actual* service. In this case, your Radarr instances `hd_bluray_web` and `uhd_bluray_web` both point to the same server. There's some confusing behavior in Recyclarr when you do this, because it thinks both of those are *separate instances of Radarr*. So in that sense, your Radarr instance is conflicting with itself.

For now, I recommend you consolidate your configuration files. Copy & paste the configuration (minus the `radarr:` root element) into the same file.

**Comment by apapushoy** [comment] 2023-07-01 07:09
I am having this same warning message and yet I do not have multiple sonarr/radarr instances. My config has one instance of radarr and one of sonarr. I assume the CF IDs are generated in Sonarr, if so, would this not be caused by a Sonarr change?

**Comment by apapushoy** [comment] 2023-07-01 08:00
> I am having this same warning message and yet I do not have multiple sonarr/radarr instances. My config has one instance of radarr and one of sonarr. I assume the CF IDs are generated in Sonarr, if so, would this not be caused by a Sonarr change?

Here's a link of my config: https://pastebin.com/dGyEG2mJ

**Comment by jpdsc** [comment] 2023-07-01 08:26
To add. SiC is the only CF doing this, I have multiple same CF's across different configs and those aren't giving a warning.
Such as AM

**Comment by apapushoy** [comment] 2023-07-01 11:19
It happened for a large number of CFs in my case. Here's the log: [recyclarr_2023-07-01_14-35-28.debug.log](https://github.com/recyclarr/recyclarr/files/11925665/recyclarr_2023-07-01_14-35-28.debug.log)

**Comment by rcdailey** [comment] 2023-07-01 14:41
@apapushoy Please archive & attach your `cache` directory and also provide the corresponding `verbose.log` file. I will take a look.

@jpdsc Please consolidate your config files and test again. If the issue still happens, I will dig further. It's easier if we can rule out one thing at a time.

For now I will reopen since another has posted about the issue here. I certainly want to make sure there's no bug here.

**Comment by apapushoy** [comment] 2023-07-01 16:05
Here you go:
[recyclarr_verbose.tar.gz](https://github.com/recyclarr/recyclarr/files/11926599/recyclarr_verbose.tar.gz)
[cache.tar.gz](https://github.com/recyclarr/recyclarr/files/11926601/cache.tar.gz)

Thanks.

**Comment by rcdailey** [comment] 2023-07-01 17:06
@apapushoy Can you walk me through anything unusual you have done with your Radarr instance named `movies`? Your cache says you have those CFs already on your instance but with different IDs. Typically this happens when you import them manually, or change the Radarr instance or installation in some way (for example, `localhost:7878` pointed at an old instance and you installed a new one in its place).

The only way IDs get confused like this is when something happens to the CFs in Radarr that Recyclarr didn't know about, including changing the URL to a different instance (indirectly).

Understanding the history of what you did will reveal the root cause.

If you aren't interested in the reason/cause, simply set `replace_existing_custom_formats: true`, performing a single `recyclarr sync` and then changing that setting back to `false` will clear the warnings.

**Comment by apapushoy** [comment] 2023-07-02 01:43
I'm running everything on a NAS via docker. Initially the Starr apps talked to each other via the network hostname of the NAS. However, this generated 380k unnecessary DNS queries to the gateway over the course of the week so I changed everything to refer to the individual docker container names since they're all on the same network. So recyclarr config went from http://nas to http://radarr. 

`replace_existing_custom_formats` wasn't aware of this option, had to manually remove all the CFs by hand and resync.

**Comment by rcdailey** [comment] 2023-07-02 15:15
After removing the CFs manually and doing the resync, did the warnings go away or did they remain?

When you changed from the network hostname to docker DNS names, I presume this resulted in the `base_url` values changing. If so, that would have generated a new cache, but the warnings would have still been there because the CFs already existed.

Either deleting all the CFs by hand or flipping `replace_existing_custom_formats` to `true` would have resolved the warnings. Please let me know!

**Comment by rcdailey** [comment] 2023-07-02 17:12
I'm going to close this issue again. I did significant testing yesterday and I was not able to reproduce the issue.

@apapushoy I think it would have helped if you were more clear about whether or not these are *current* or *past* symptoms. I originally assumed it was the former. I'll watch for your answer to my last rely just in case, but I suspect it's the latter. If so, there was never a bug to begin with. You have a misunderstanding of the behavior. While I recognize is isn't as straightforward as I'd like it to be, you cannot swap your `base_url` and expect Recyclarr to know it's the same instance of Radarr. The [upgrade guide for v5.0](https://recyclarr.dev/wiki/upgrade-guide/v5.0/#replace-existing-custom-formats) pretty clearly states the workaround for this situation, and the [YAML reference guide](https://recyclarr.dev/wiki/yaml/config-reference/#custom-format-settings) has documentation for `replace_existing_custom_formats`.

I'm not really sure what I could do to make this less confusing for people. Contributions are always welcome for the wiki if someone feels like there's an improvement to be made.

Thanks to everyone for providing logs and other information to help rule out any bugs.

**Closed by rcdailey** 2023-07-02 17:12 UTC
Labels: bug

**Comment by apapushoy** [comment] 2023-07-02 23:19
> After removing the CFs manually and doing the resync, did the warnings go away or did they remain?
> 
> When you changed from the network hostname to docker DNS names, I presume this resulted in the `base_url` values changing. If so, that would have generated a new cache, but the warnings would have still been there because the CFs already existed.
> 
> Either deleting all the CFs by hand or flipping `replace_existing_custom_formats` to `true` would have resolved the warnings. Please let me know!

This was a current issue at the time of posting but I didn’t want to leave it in that state so I took manual action. I had removed the CFs by hand, resynced and the warnings disappeared.

**Comment by apapushoy** [comment] 2023-07-02 23:24
> I'm going to close this issue again. I did significant testing yesterday and I was not able to reproduce the issue.
> 
> @apapushoy I think it would have helped if you were more clear about whether or not these are _current_ or _past_ symptoms. I originally assumed it was the former. I'll watch for your answer to my last reply just in case, but I suspect it's the latter. If so, there was never a bug to begin with. You have a misunderstanding of the behavior. While I recognize is isn't as straightforward as I'd like it to be, you cannot swap your `base_url` and expect Recyclarr to know it's the same instance of Radarr. The [upgrade guide for v5.0](https://recyclarr.dev/wiki/upgrade-guide/v5.0/#replace-existing-custom-formats) pretty clearly states the workaround for this situation, and the [YAML reference guide](https://recyclarr.dev/wiki/yaml/config-reference/#custom-format-settings) has documentation for `replace_existing_custom_formats`.
> 
> I'm not really sure what I could do to make this less confusing for people. Certainly, if you don't read the documentation, that'll cause problems and I can't help you there. Contributions are always welcome for the wiki if someone feels like there's an improvement to be made.
> 
> Thanks to everyone for providing logs and other information to help rule out any bugs.

Thanks for the tip regarding the upgrade docs. I did run a migration command but hadn’t considered checking the wiki. Having so many containers, I just use Pullio to perform updates and that makes it easy to miss release-related instructions. At least with the main Starr apps there’s a release notes page that’s easy to check. Also the cron nature of recyclarr makes it easy to miss issues one keeps in mind to periodically check the logs, which I happened to do because of the host name change.

**Comment by rcdailey** [comment] 2023-07-03 04:08
> just use Pullio to perform updates and that makes it easy to miss release-related instructions

I recommend you use the major version number docker tag. In this case, it would be `5`. It's a good balance between maintenance burden and keeping things working. I can pretty much guarantee you that every major upgrade will have breaking changes. Using the tag `5` will still get you automatic feature and bugfix releases but require manual change/review for breaking changes. Then all you need to do is head over to the Upgrade Guide section of the wiki and see what you need to do before changing it to `6`.

Glad you got everything worked out.
