### ISSUE TITLE
Configuration Defined Custom Formats

### ISSUE THREAD

**Issue by mcinj** [recyclarr/recyclarr#386] opened 2024-12-20 13:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This project is perfection and the trash custom formats are wonderful; there are a few custom formats I have specific to certain sources I would like to define and use. Configuration as code if you will.

Feature Request: Ability to define and reference our own custom formats.

Maybe my search-fu is terrible and this exists, but I could not find it when I did look.

**Comment by rcdailey** [comment] 2024-12-20 13:48
Thanks for you kind words. This is a duplicate of #218. Be sure to upvote that one!

**Closed by rcdailey** 2024-12-20 13:48 UTC
Labels: enhancement
