### ISSUE TITLE
Use Git repo as `configs` folder

### ISSUE THREAD

**Issue by owine** [recyclarr/recyclarr#220] opened 2023-12-12 18:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Allow passing a Git repo to Recyclarr via settings.yml which is treated as the equivalent as a `configs` folder. On each sync, Recyclarr updates the repo and parses the files for the sync. This allows a user to manage config files via a Git repo similar to managing a TRaSH Guides fork.

**Comment by rcdailey** [comment] 2023-12-12 20:04
Here's a thought. Do `git init` inside of your `/config/configs` directory. Before you run `recyclarr sync`, do a `git pull` in that directory. Would that not achieve the desired result?

**Comment by owine** [comment] 2023-12-12 20:22
Yes this does work and is my current workflow, but requires separate automation to automate pulling the changes prior to recyclarr's automated runs.

**Comment by rcdailey** [comment] 2023-12-13 13:27
Can you help me understand the real problem a little better? For example, you said "requires separate automation". What "automation" tooling are you using? I assume it's more than just cron and a script.

**Comment by owine** [comment] 2023-12-13 13:46
It is indeed just a simple script on cron. My thought was just because Recyclarr already handles git for the guides that handling one for configs could be a nice feature as well

**Comment by rcdailey** [comment] 2023-12-13 13:58
There's a few reasons why git support for the templates and guide repo are different from what you're asking for:

- The application, by design, operates on the latest version of the guides. It used to do this by just grabbing the files directly from github via its API, but due to rate limiting, the implementation changed to use git clones. So pulls there are just an implementation detail to fulfill this requirement.
- The application cannot work without these repos, and there should be no additional steps required by users to obtain this data, so as a result, Recyclarr handles obtaining and updating them in the background.

Configuration files, however, are completely up to the user to provide. Not all users put them in git, and it's not a requirement for them to be in git. I feel like for these reasons, the two are different as far as git support goes.

I have to carefully consider whether or not this is something built on top of (and separate from) Recyclarr itself, to supplement some functionality, or a requirement for Recyclarr to function. I see this going in the former bucket.

On that note, I am not sure why it's such a bad idea to have a script that simply does something like this:

```sh
cd /home/you/.config/recyclarr/configs
git pull
recyclarr sync
```

Right now, I'm of the mind that adding this functionality into git would add a lot of complication and overhead that isn't strictly valuable when you can write a script as simple as above. This is on top of all the reasons I mentioned above from a design standpoint.

I think it's a great idea how you're keeping your configs in git, though!

**Comment by rcdailey** [comment] 2023-12-28 22:57
I'm going to go ahead and close this issue, as I have no immediate or long term plans to address this. I personally feel it is reasonable to run git commands prior to Recyclarr, so I don't see a need for this specific functionality. I appreciate the report, though!

**Closed by rcdailey** 2023-12-28 22:57 UTC
Labels: enhancement
