### ISSUE TITLE
parsing error - unable to run. (UNRAID/DOCKER)

### ISSUE THREAD

**Issue by JonzaUK** [recyclarr/recyclarr#87] opened 2022-06-08 10:56 UTC
Just checked the logs of recyclarr noticed some errors tried a manual run using `recyclarr sonarr` in the console.

```[INF] Processing server http://hostname:8989
System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: #. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at TrashLib.Sonarr.ReleaseProfile.Guide.LocalRepoReleaseProfileJsonParser.<>c__DisplayClass4_0.<<GetReleaseProfileDataImpl>b__0>d.MoveNext() in D:\a\recyclarr\recyclarr\src\TrashLib\Sonarr\ReleaseProfile\Guide\LocalRepoReleaseProfileJsonParser.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TrashLib.Sonarr.ReleaseProfile.Guide.LocalRepoReleaseProfileJsonParser.GetReleaseProfileDataImpl() in D:\a\recyclarr\recyclarr\src\TrashLib\Sonarr\ReleaseProfile\Guide\LocalRepoReleaseProfileJsonParser.cs:line 26
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at TrashLib.Sonarr.ReleaseProfile.Guide.LocalRepoReleaseProfileJsonParser.GetReleaseProfileData() in D:\a\recyclarr\recyclarr\src\TrashLib\Sonarr\ReleaseProfile\Guide\LocalRepoReleaseProfileJsonParser.cs:line 44
   at TrashLib.Sonarr.ReleaseProfile.ReleaseProfileUpdater.Process(Boolean isPreview, SonarrConfiguration config) in D:\a\recyclarr\recyclarr\src\TrashLib\Sonarr\ReleaseProfile\ReleaseProfileUpdater.cs:line 37
   at Recyclarr.Command.Services.SonarrService.Process(ISonarrCommand cmd) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\Services\SonarrService.cs:line 73
   at Recyclarr.Command.Services.ServiceBase`1.Execute(T cmd) in D:\a\recyclarr\recyclarr\src\Recyclarr\Command\Services\ServiceBase.cs:line 18```

**Comment by skayo** [comment] 2022-06-08 11:28
Looks like Recyclarr is trying to parse a Markdown file as JSON?

**Comment by skayo** [comment] 2022-06-08 11:32
Okay I see the problem... TRaSH added a deprecation warning to the beginning of his JSON files and Recyclarr is trying to parse it: https://github.com/TRaSH-/Guides/blob/c8b1967f925b8bcaa10f29cc87222390efa9bd5a/docs/json/sonarr/optional.json#L1

**Comment by StewGoin** [comment] 2022-06-08 11:43
Same issue cropped up, I saw TRaSH said we should move to optionals.json as optional.json won't be updated anymore too.

**Comment by skayo** [comment] 2022-06-08 11:46
Yeah the problem is that Recyclarr parses all JSON files in that directory, so it will have to explicitly ignore the deprecated JSON file

**Comment by austinwbest** [comment] 2022-06-08 12:06
It should have never used that file. That file was not in use when he switched over to json for sonarr and honestly just needs deleted.

I think it is just reading in all the json files in the folder generically and that is the problem because that file is not used for anything

**Comment by rcdailey** [comment] 2022-06-08 12:56
Recyclarr has to read all of the files from the directory into memory in order to gain access to the `trash_id` value and determine if it matches the corresponding ID specified by the user in their configuration YAML. I'd like to be able to only read in the files the user specified trash IDs for, but that's not possible when the primary key is data inside the file itself.

What I can do is ignore failures and any files that fail to parse just get spit out as a warning. This might also encourage users to have Trash fix or delete files that do not parse correctly.

In my mind, the only files in this directory should be valid, parsable release profile JSON files. I don't know if @austinwbest intended that to be a guarantee.

**Comment by skayo** [comment] 2022-06-08 13:08
TRaSH just merged my PR that should fix this problem for now. Can you confirm that it works now, @JonzaUK?

**Comment by austinwbest** [comment] 2022-06-08 13:28
> 

Mine is more forgiving so it doesn't really matter :)

However that file doesn't even need to be there, it is the one you mentioned you would PR to remove.

**Closed** 2022-06-08 16:22 UTC
Labels: bug, sonarr
